application: glitch-python-contrib
version: 1
runtime: python
api_version: 1

handlers:
- url: /
  script: home.py

- url: /oauth/.*
  script: oauth.py

- url: /logout/
  script: logout.py

- url: /.*
  script: not_found.py
